name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: read
  issues: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Enable Corepack & Prepare Yarn
        run: corepack enable && corepack install
      - name: Install Dependencies
        id: yarn-install
        run: yarn install --immutable

      - name: Check Format
        id: yarn-format-check
        run: yarn run format:check

      - name: Lint
        id: yarn-lint
        run: yarn run lint

      - name: Test
        id: yarn-test
        run: yarn run test
